"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

OPTIONS = {
    'iconfile':'PythonApplet.icns',
}

setup(
    app=['../PaddleBall.py'],
    options={'py2app': OPTIONS},
    setup_requires=["py2app"],
)
